### ISSUE TITLE
[S3 - PBI7] Pengguna dapat mengisi data rekam medisnya

### ISSUE THREAD

**Issue by audhinisy** [SI-RPL-2021/SI4208-ANTRI.IN#10]
Saya sebagai user ingin bisa mengisi data rekam medis
sehingga saya bisa melakukan reservasi
https://www.figma.com/file/DnT9dhW4upP8qVoNX4RUj7/ANTRI.IN?node-id=0%3A1
![RSUD BOJONGSWAN 2](https://user-images.githubusercontent.com/71873818/111753891-f4b15b00-88c9-11eb-9b22-82776de29a92.png)

**Comment by naufalmf26** [comment]
Update desain mockup pengisian rekam medis
![mengisi rekammedis](https://user-images.githubusercontent.com/71960708/122437772-3a161f00-cfc4-11eb-85c7-f88efca6600a.png)
