### ISSUE TITLE
[S3 - PBI9] Pengguna dan dokter dapat melakukan konsultasi berobat online

### ISSUE THREAD

**Issue by aryaimmanuel** [SI-RPL-2021/SI4208-ANTRI.IN#11]
Saya sebagai pengguna ingin dapat melakukan konsultasi berobat dengan dokter secara online sehingga dapat melakukan konsultasi

https://www.figma.com/file/DnT9dhW4upP8qVoNX4RUj7/ANTRI.IN?node-id=0%3A1

**Comment by octobersthings** [comment]
![image](https://user-images.githubusercontent.com/71837231/122433675-a4c55b80-cfc0-11eb-966b-a46a6c36a298.png)

![image](https://user-images.githubusercontent.com/71837231/122433638-9d9e4d80-cfc0-11eb-88d6-73ff582f651a.png)

![image](https://user-images.githubusercontent.com/71837231/122433584-91b28b80-cfc0-11eb-86d1-7e7a622c858c.png)

**Comment by titokaji** [comment]
Menyempurnakan sketsa tampilan chat dokter menggunakan figma. #11
![TAMPILAN CHAT](https://user-images.githubusercontent.com/71874576/122443971-49986680-cfca-11eb-8298-6527ad1a1114.png)

**Comment by titokaji** [comment]
Menyempurnakan tampilan chat konsultasi dengan dokter 
![CHAT KONSULTASI](https://user-images.githubusercontent.com/71874576/122444303-9a0fc400-cfca-11eb-80ac-13c59f173dcf.png)
